206 entrer sa localisation (#208)
* add tree questions

* update display and add method to read YAML

* correct yaml

* Change from question to question

Next: Update SelectedAnswer to no have duplicate
-> only read from memory

* prevent user from spamming answer

Not optimal, should change to change design when button selected

* Update question

Update to do: remove key not answered in the last flow

(not relevant anymore)

* add isroot tag

* remove root attribute

* only send relevant answers

* add confirm button

* add comment to questions file v1

* Update backend - not tested

* remove print statement and add status for
question first time

* Update backend to handle discriminating

ERROR: block not working (add to group rejected)

* correct bug in blockedUser

* add discriminating questions

* update config

* Update fr-2.yaml

Bon bah premier essai. 2 questions discriminantes, le reste c'est cadeau. N'hésitez pas à donner d'autres idées de questions ou un retour sur celles-ci !

Signed-off-by: Alice Etrx <104730932+AliceETRX@users.noreply.github.com>

* ids plus lisibles

modifications des ids des questions et réponses.

Signed-off-by: Alice Etrx <104730932+AliceETRX@users.noreply.github.com>

* update question to limit error

correct error in yaml files

Co-authored-by: Alice Etrx <104730932+AliceETRX@users.noreply.github.com>